language: node_js
node_js:
  - '0.10'
branches:
  only:
  - master
before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config user.email "bravocado.project@gmail.com"
  - git config user.name "bravocado"
script:
  - npm install grunt
  - npm install grunt-cli
  - grunt travis
after_script:
  - git clone https://bravocado:${GH_TOKEN}@github.com/bravocado/bower-anila.git
  - cp -r dist/assets/* bower-anila/
  - cd bower-anila
  - git remote rm origin
  - git remote add origin https://bravocado:${GH_TOKEN}@github.com/bravocado/bower-anila.git
  - git add .
  - git commit -m "adding Anila to bower-anila"
  - git push -fq origin master
  - echo -e "Done with magic\n"
env:
  global:
    secure: OrlGu5F9JHCrFfUX0oR9LxXc89uwy82Cd66NdBniYeKYvRnAkeKyIw7JOfwaUj613JDDkA0H0g7p9UlYnhsr5b03zkPkNTUaZMRQ1hw8k0Wzck0lNln5oeWf7knG422g/w7hb0j4Sfty3QIVwq5/LXIKLL4l2ZxM+SUtbU8/yC0=
notifications:
  email: 
    recipients:
      - bravocado.project@gmail.com
