language: node_js
node_js:
  - '0.10'
branches:
  only:
  - master
before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.email "bravocado.project@gmail.com"
  - git config --global user.name "bravocado"
script:
  - npm install
  - gulp build
after_script:
  - git clone https://bravocado:${GH_TOKEN}@github.com/bravocado/bower-anila.git
  - cp -r dist/* bower-anila/
  - cd bower-anila
  - git remote rm origin
  - git remote add origin https://bravocado:${GH_TOKEN}@github.com/bravocado/bower-anila.git
  - git add .
  - git commit -m "adding Anila to bower-anila"
  - git push -fq origin master
  - echo -e "Done with magic\n"
env:
  global:
    secure: BVl/1lIoDD9yroN6LR98q/tvslqFYT054E40jIaVSdCRoVpF7CwiDSGHIlWAAgnTwwjUp7H3618jj3gL4HrIo/NTpnoiScfTZNvi3PAivGITyyJlvrsv5ijOWXdgvjCyAri6jW0UBUwMQ7VkrHOwMeTlr2Sfoqfr+DfB2Z3pSok=
notifications:
  email: 
    recipients:
      - bravocado.project@gmail.com
