language: node_js
node_js:
- '0.10'
branches:
  only:
  - development
script:
- npm install grunt
- npm install grunt-cli
- grunt travis
notifications:
  email:
    recipients:
    - bravocado.project@gmail.com
env:
  global:
    secure: BVl/1lIoDD9yroN6LR98q/tvslqFYT054E40jIaVSdCRoVpF7CwiDSGHIlWAAgnTwwjUp7H3618jj3gL4HrIo/NTpnoiScfTZNvi3PAivGITyyJlvrsv5ijOWXdgvjCyAri6jW0UBUwMQ7VkrHOwMeTlr2Sfoqfr+DfB2Z3pSok=
after_script: update-dist.sh